runner:
  phpstan:
    cmd: ./vendor/bin/phpstan --memory-limit=1G --error-format=raw
    format: phpstan
    level: error
  eslint:
    cmd: ./node_modules/.bin/eslint ./resources/**/*.{js,vue} -f compact
    format: eslint-compact
    level: error
  php-cs-fixer:
    cmd: ./vendor/bin/php-cs-fixer fix --dry-run --format checkstyle
    format: checkstyle
    level: warning

