services:
  php:
    build:
      context: ./
      dockerfile: ./deploy/local/php.Dockerfile
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      DB_HOST: mariadb
    networks:
      - default
      - spotifynt
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9000:9000"
    command: sh -c "composer i && php-fpm"
    user: 1000:1000
    volumes:
      - .:/var/www/html

  backend:
    image: nginxinc/nginx-unprivileged:1.27.0
    user: 1000:1000
    networks:
      - default
      - spotifynt
    depends_on:
      - php
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
      - ./deploy/local/site.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/up"]

  worker:
    build:
      context: ./
      dockerfile: ./deploy/local/php.Dockerfile
    networks:
      - spotifynt
      - default
    depends_on:
      - php
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      DB_HOST: mariadb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "php artisan queue:listen --queue=default --tries=3 --timeout=300"
    user: 1000:1000
    volumes:
      - .:/var/www/html
    deploy:
      mode: replicated
      replicas: 5


  # utils
  mailpit:
    image: axllent/mailpit:v1.25.1
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8025/"]


  # shared
  mariadb:
    image: mariadb:11.3.2
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: true
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: healthcheck.sh --su-mysql --connect --innodb_initialized

  minio:
    image: minio/minio:RELEASE.2024-06-29T01-20-47Z
    ports:
      - 9090:9000 # Minio
      - 9001:9001 # Web UI
    networks:
      - default
      - spotifynt
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    command: server /data --console-address ":9001"

  minio-createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio ${AWS_ENDPOINT} ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY};
      /usr/bin/mc mb myminio/public-bucket;
      /usr/bin/mc anonymous set public myminio/public-bucket;
      exit 0;
      "

  redis:
    image: redis:8.0
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    command: ["redis-server", "--save 3600 10"]

  typesense:
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors'

volumes:
  mariadb_data:
  redis_data:
  minio_data:
  typesense_data:

networks:
  spotifynt:
    external: true
