version: '3.9'
services:
  php:
    image: serversideup/php:7.4-fpm-apache
    ports:
      - 127.0.0.1::80
    volumes:
      - .:/var/www/html
    labels:
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${TRAEFIK_HOST}`)"
    networks:
      - traefik_default
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      AUTORUN_LARAVEL_STORAGE_LINK: false
    restart: unless-stopped

  db:
    image: percona:5.7-centos
    ports:
      - 127.0.0.1::3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - traefik_default
    restart: unless-stopped

volumes:
  db:

networks:
  traefik_default:
    external: true
