version: '3.9'
services:
  php:
    build: ./provision/php_hostgator
    ports:
      - 127.0.0.1::80
    volumes:
      - .:/var/www/html
    labels:
      - "traefik.http.routers.${APP_NAME}.rule=Host(`/${TRAEFIK_HOST}`)"
    networks:
      - traefik_default

  db:
    image: percona:5.7-centos
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
    networks:
      - traefik_default

volumes:
  db:

networks:
  traefik_default:
    external: true
