version: '3.9'
services:
  php:
    image: serversideup/php:8.1-fpm-apache
    volumes:
      - .:/var/www/html
    environment:
      AUTORUN_ENABLED: "false"
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      PHP_MEMORY_LIMIT: "1G"
      PHP_MAX_EXECUTION_TIME: 300
      SSL_MODE: "off"
      PUID: 1000
      PGID: 1000
    network_mode: host

  queue:
    image: serversideup/php:8.1-cli
    volumes:
      - .:/var/www/html
    command: ["su", "webuser", "-c", "php artisan queue:listen --queue=high,default,low"]
    network_mode: host
    environment:
      PHP_MEMORY_LIMIT: "1G"
      PHP_MAX_EXECUTION_TIME: 300
      PUID: 1000
      PGID: 1000

  db:
    image: mariadb:10.6.16
    environment:
      MARIADB_DATABASE: database
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
    network_mode: host

  beets:
    build: https://github.com/vicholp/docker-beets.git#master
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
    network_mode: host
    volumes:
      - ./provision/beets/config.yaml:/config/config.yaml
      - beet_music:/music
      - ./provision/beets/music:/music_temp

volumes:
  db:
  beet_music:
