version: '3.9'
services:
  php:
    image: serversideup/php:8.1-fpm-apache
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      AUTORUN_LARAVEL_STORAGE_LINK: "false"
    restart: unless-stopped

  db:
    image: percona:5.7-centos
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

volumes:
  db:
