version: '3.9'
services:
  php:
    image: serversideup/php:8.1-fpm-apache
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      PHP_MEMORY_LIMIT: "512M"
      AUTORUN_LARAVEL_STORAGE_LINK: "false"
    network_mode: host

  db:
    image: percona:5.7-centos
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
    network_mode: host

volumes:
  db:
