/* eslint-disable import/prefer-default-export */

export const PLAYER_PLAYLIST_ADD_ALBUM = 'PLAYER_PLAYLIST_ADD_ALBUM';
export const PLAYER_PLAYLIST_ADD_TRACK = 'PLAYER_PLAYLIST_ADD_TRACK';
export const PLAYER_PLAYLIST_SET_INDEX = 'PLAYER_PLAYLIST_SET_INDEX';
export const PLAYER_SET_BACKGROUND_COLOR = 'PLAYER_SET_BACKGROUND_COLOR';
export const PLAYER_SET_ACTUAL_TRACK = 'PLAYER_SET_ACTUAL_TRACK';

export const PLAYER_PLAY = 'PLAYER_PLAY';
export const PLAYER_PAUSE = 'PLAYER_PAUSE';
export const PLAYER_SET_TIME = 'PLAYER_SET_TIME';

